# Generated by Django 4.2.10 on 2024-03-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='location_name',
            new_name='software_name',
        ),
    ]
