# Generated by Django 4.2.10 on 2024-03-09 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emp_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='emp_phone',
            new_name='phone',
        ),
    ]
