# Generated by Django 4.2.10 on 2024-03-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_rename_emp_email_employee_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
