# Generated by Django 4.2.10 on 2024-03-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_remove_employee_phone_employee_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.AddField(
            model_name='employee',
            name='usr_email',
            field=models.EmailField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='usr_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='usr_phone',
            field=models.IntegerField(null=True),
        ),
    ]
