# Generated by Django 4.2.10 on 2024-03-09 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
